### ISSUE TITLE
Create of Group Chat Fail

### ISSUE THREAD

**Issue by zxiu** [guardianproject/ChatSecureAndroid#608]
Hello, 
i am developing a fork of ChatSecureAndroid.
I am not able to create group chat with the client.
I get follow errors in logcat:

01-06 10:09:12.456: E/GB.ImApp(7252): error creating MUC
01-06 10:09:12.456: E/GB.ImApp(7252): item-not-found(404) This room is locked
01-06 10:09:12.456: E/GB.ImApp(7252): 	at org.jivesoftware.smackx.muc.MultiUserChat.create(MultiUserChat.java:356)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at info.guardianproject.otr.app.im.plugin.xmpp.XmppConnection$XmppChatGroupManager.createChatGroupAsync(XmppConnection.java:531)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at info.guardianproject.otr.app.im.plugin.xmpp.XmppConnection.findOrCreateParticipant(XmppConnection.java:1592)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at info.guardianproject.otr.app.im.plugin.xmpp.XmppConnection.findOrCreateSession(XmppConnection.java:1576)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at info.guardianproject.otr.app.im.plugin.xmpp.XmppConnection.access$13(XmppConnection.java:1572)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at info.guardianproject.otr.app.im.plugin.xmpp.XmppConnection$2.processPacket(XmppConnection.java:1254)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at org.jivesoftware.smack.Connection$ListenerWrapper.notifyListener(Connection.java:833)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at org.jivesoftware.smack.PacketReader$ListenerNotification.run(PacketReader.java:482)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-06 10:09:12.456: E/GB.ImApp(7252): 	at java.lang.Thread.run(Thread.java:841)

I tested with adium on our server and muc function works fine (create/join/message).

Btw, when i create group chat, the default server in the dialog is always conference.dukgo.com, not the server of jabber id. I could change it in code but maybe it is not supposed so? 

Regards

**Comment by zxiu** [comment]
Another relative issue:
after i "create" group chat as above, the room is actually not created in server, but it is shown in Chat List.
I can write the message in that chat, even though the server will not handle it.
And i can't delete that chat in list. It disappear after i restart chatsecure client.
