### ISSUE TITLE
File received doesnot open - says file not found

### ISSUE THREAD

**Issue by hearbeathorror** [guardianproject/ChatSecureAndroid#675]
Hi,

I have been playing with the source code for a few days, and i noticed that when a file is being sent from the source code apk in this repo to an apk (Chat Secure's) from the play store, the file is received pretty well and on export it also plays. But when the file is sent from the play store version to this repo's version, the file is not received correctly. It gives the following error:

05-02 02:05:36.258: E/GB.ImApp(3215): java.io.FileNotFoundException: /3/download/IMG_20150427_131754%281%29.jpg: open failed: ENOENT (No such file or directory)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.libcore.io.IoBridge.open(IoBridge.java:75)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.iocipher.FileInputStream.<init>(FileInputStream.java:74)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.ChatFileStore.getThumbnailVfs(ChatFileStore.java:122)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.MessageView.getThumbnail(MessageView.java:550)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.MessageView$3.doInBackground(MessageView.java:522)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.MessageView$3.doInBackground(MessageView.java:1)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at java.lang.Thread.run(Thread.java:818)
05-02 02:05:36.258: E/GB.ImApp(3215): Caused by: info.guardianproject.libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.libcore.io.Posix.open(Native Method)
05-02 02:05:36.258: E/GB.ImApp(3215): 	at info.guardianproject.libcore.io.IoBridge.open(IoBridge.java:59)
05-02 02:05:36.258: E/GB.ImApp(3215): 	... 11 more
05-02 02:05:41.275: E/GB.ImApp(3215): unable to read vfs thumbnail
05-02 02:05:41.275: E/GB.ImApp(3215): java.io.FileNotFoundException: /3/download/IMG_20150427_131754%281%29.jpg: open failed: ENOENT (No such file or directory)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.libcore.io.IoBridge.open(IoBridge.java:75)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.iocipher.FileInputStream.<init>(FileInputStream.java:74)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.ChatFileStore.getThumbnailVfs(ChatFileStore.java:122)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.MessageView.getThumbnail(MessageView.java:550)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.MessageView$3.doInBackground(MessageView.java:522)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.otr.app.im.app.MessageView$3.doInBackground(MessageView.java:1)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at java.lang.Thread.run(Thread.java:818)
05-02 02:05:41.275: E/GB.ImApp(3215): Caused by: info.guardianproject.libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.libcore.io.Posix.open(Native Method)
05-02 02:05:41.275: E/GB.ImApp(3215): 	at info.guardianproject.libcore.io.IoBridge.open(IoBridge.java:59)
05-02 02:05:41.275: E/GB.ImApp(3215): 	... 11 more

could you please tell me how to store the file correctly? Or probably hint where i could start rectifying this issue from?

Thanks
Dhara

**Comment by n8fr8** [comment]
Did you change the code in anyway? Not sure what the problem is, but it seems to relate to just getting a thumbnail that may not exist.
