### ISSUE TITLE
Unable to use "Secret Identity" in Gingerbread

### ISSUE THREAD

**Issue by abshda** [guardianproject/ChatSecureAndroid#739]

**Comment by n8fr8** [comment]
Why did you close it?

**Comment by abshda** [comment]
Filed it here too https://dev.guardianproject.info/issues/6663

**Comment by AbdulSamadQureshi** [comment]
Hello Guys, I am having a crash while trying to run ChatSecure on my nexus 5 and galaxy nexus emulators, following is the crash log, please fix it soon as possible


02-29 00:19:05.591: E/(2057): UID 10035 asks for /proc/cpuinfo
02-29 00:19:05.591: E/(2057): Read ID 10051 from file /data/data/.appwithABI2
02-29 00:19:05.591: E/(2057): Unable to open file /data/data/.appwithABI2neon
02-29 00:19:05.591: E/(2057): UID 10035 is not in ARM UID list files
02-29 00:19:17.039: E/Database(2057): sqlite_config failed error_code = 21. THIS SHOULD NEVER occur.
02-29 00:19:17.119: E/AndroidRuntime(2057): FATAL EXCEPTION: main
02-29 00:19:17.119: E/AndroidRuntime(2057): java.lang.RuntimeException: Unable to start activity ComponentInfo{info.guardianproject.otr.app.im/info.guardianproject.otr.app.im.app.NewChatActivity}: android.view.InflateException: Binary XML file line #47: Error inflating class fragment
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.ActivityThread.access$600(ActivityThread.java:130)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.os.Looper.loop(Looper.java:137)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at java.lang.reflect.Method.invoke(Method.java:511)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at dalvik.system.NativeStart.main(Native Method)
02-29 00:19:17.119: E/AndroidRuntime(2057): Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class fragment
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:256)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.Activity.setContentView(Activity.java:1867)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at info.guardianproject.otr.app.im.app.NewChatActivity.onCreate(NewChatActivity.java:190)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.Activity.performCreate(Activity.java:5008)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	... 11 more
02-29 00:19:17.119: E/AndroidRuntime(2057): Caused by: java.lang.IllegalArgumentException: Binary XML file line #47: Must specify unique android:id, android:tag, or have a parent with an id for info.guardianproject.otr.app.im.app.AccountsFragment
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2260)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:31)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:80)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at info.guardianproject.otr.app.im.app.NewChatActivity.onCreateView(NewChatActivity.java:1)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
02-29 00:19:17.119: E/AndroidRuntime(2057): 	... 24 more
